### ISSUE TITLE
total_size is not the number of nodes

### ISSUE THREAD

**Issue by remysucre** [egraphs-good/egg#164] opened 2022-01-31 18:33 UTC
`total_size` returns the hashcons size, but that's not always the same as the number of nodes. This can be verified with replacing `total_size` with the following: 

    pub fn total_size(&self) -> usize {
        // self.memo.len()
        let mut cnt = 0;
        for c in self.classes() {
            for _n in &c.nodes {
                cnt += 1;
            }
        }

        assert_eq!(cnt, self.memo.len());

        return cnt;
    }

I suspect this is because we don't remove pruned nodes from the hashcons.

**Comment by mwillsey** [comment] 2022-02-01 00:10
I think this is the intended behavior, since you can always calculated the "pruned" size as you did above, but there's no other way to get the memo size.

Do you think we should change that?

**Comment by remysucre** [comment] 2022-02-01 02:14
At least the doc should be changed. Besides that, removing pruned nodes from the hash cons could have benefits. I've seen the hash cons holding at least 2X actual nodes.

**Comment by Bastacyclop** [comment] 2022-02-01 08:46
Slightly off-topic: I've been wondering whether pruning without actually deleting nodes might be more efficient? Otherwise on multiple iterations the same node might be added and then pruned back over and over again? What if some nodes/classes are just tagged as being pruned and ignored by most operations -- except adding the pruned node again would simply change its tag?

**Comment by mwillsey** [comment] 2024-03-22 19:49
Closing, this is now reflected in the docs.

**Closed by mwillsey** 2024-03-22 19:49 UTC
